language: python
python: 2.7
env:
  - TOX_ENV=py36
  - TOX_ENV=py35
  - TOX_ENV=py34
  - TOX_ENV=py33
  - TOX_ENV=py27
  - TOX_ENV=py26
install:
  - python -m pip install -U tox
script:
  - python -m tox -e $TOX_ENV
